### ISSUE TITLE
Reeti configuration files

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#105]
Set up *.json files in user folder to contain robot-specific information, such as IP address and joint parameters for each of our 5 robots.  And code to read in this data.

Notice hard-coded IP addresses in at least following two places.  Please check for any others:

(1) public ReetiCommandSocketConnection () 
         socket = new Socket("130.215.28.4", 12045);

(2) public ShoreFacePerceptor.Reeti ()
       String[] ptr = new String[] { "130.215.28.4" };
       CPPinterface.INSTANCE.initReetiShoreEngine(ptr, 0);

Also:
- assume that as part of setting up each physical system to go out in the field, we will manually copy the appropriate .json file from lib/reeti to always/user/Reeti.json, so that this file is always read in (no other special mechanisms required)
- In order to be independent of the file structure on the field machines, Reeti.json must be read as a _resource_ not a file.  Thus instead of 
  
    ...new FileReader("lib/reeti/Fili.json")..
  
  you need assume that always/user will be on the classpath and use:
  
  ```
    new InputStreamReader(getClass().resourceAsStream("Reeti.json"))
  ```

**Comment by mshayganfar** [comment]
I have all 5 json files now. I also wrote the code to read from json files. The question is where do we need to put this file which contains a class helping us to read all the values from the json file.

**Comment by mshayganfar** [comment]
I made a new file called ReetiJsonConfiguration.java beside all other Reeti files. There's also a new jar file that I am using to parse jason files. I also put this file in the lib folder beside other jar files.

**Comment by mshayganfar** [comment]
I should mention that I implemented this in java. I was wondering whether I should implement the same thing in C# or we should have another mechanism to send IP address in C# side.

**Comment by mshayganfar** [comment]
This issue is done.

**Comment by mshayganfar** [comment]
This issue also can be closed.
