### ISSUE TITLE
Agent drawing card is not evident

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#107]
When agent draws a card from either the discard or new stack, it just appears (face down) in her hand (which is not very noticeable).

What is needed is an animation of the card moving from the stack to her hand, similar to what you see when the user draws a card.

**Comment by candysidner** [comment]
If this code is going to be a bear to change, we may have to punt on this.  Take a look and let Candy know.

**Comment by charlesrich** [comment]
Closing since study was not a problem
