### ISSUE TITLE
Install AlwaysOn sofware on all Reeti's

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#109]
The way this should simply work is, on each robot:

(1) Clone the main always-on/always Git repository (you can only check out a whole repository---it includes lots of stuff you are not using, but don't worry about it).

(2) Run the appropriate (single) make file.

This means that all the libraries that the system depends on (other than basic Linux) need to be included in appropriate folders in Git repository.

Then to update, all you have to do is to do a 'pull' request and call the make file again.

-CR

P.S. Obviously, while you are debugging this on one particular Reeti, you will be running in a personal fork.  But each machine should have a clone of the main trunk for fielding.

**Comment by mshayganfar** [comment]
I have updated all the five Reeties, installed git on all of them (tricky! :-), pulled Always-On on all.
I also have the make file ready, but I assume it might need some tweaks to work properly.

**Comment by mshayganfar** [comment]
This is totally done. I made a pull request.
