### ISSUE TITLE
Week Display doesn't go away after finish new event

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#11]
After finishing a new event, I think the display should go back to agent/menu only.

**Comment by mbehrooz** [comment]
I think it makes sense if the calendar stays there. Assume you make an event for Today, then you look at tomorrow and you see another event and you want to add something next to it which follows today's event... I generally mean looking at calendar while doing operations on it makes sense to me. But please let me know what you think. Thnaks.

**Comment by candysidner** [comment]
I will retest and let you know.

**Comment by mbehrooz** [comment]
So based on our conversation above, do you think it is fine to keep the calendar? The screen is not used by anything else either...

**Comment by charlesrich** [comment]
I think it is fine to leave it there, as long as it does not lead to any problems when it is used further.  So please test all the possible user choices after that and make sure nothing bad or weird happens.

Tx, -CR

**Comment by mbehrooz** [comment]
I tested and it does not. So this can be considered resolved.
