### ISSUE TITLE
Rummy graphics crash

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#13]
![crash](https://f.cloud.github.com/assets/2828816/743985/e5e516d6-e3f2-11e2-9d9e-32e74a54e182.png)

See attached assertion violation.   I think I was trying to draw from the discard pile when it was not my turn, i.e., while agent was doing its turn.

**Comment by mbehrooz** [comment]
This is a very old bug from the old version of rummy. Well, now the screen would be locked unless it is your turn, but the exact thing has happened only once during all my testing this week and it was caused after the stock pile got empty and all discard cards were moved to stock pile. So I have clue and will find it out about it. Just to update, thanks.

**Comment by mbehrooz** [comment]
I added a safety measure so that it does not throw an exception and it just simply does not accept the drop, if that happens (card is null). I will try to recreate this and fully debug it (even after Rummy pull req. (Jan.27.14)). Thanks.
