### ISSUE TITLE
Enroll--no profile to edit if no friends in UM

### ISSUE THREAD

**Issue by candysidner** [always-on/always#149]
In Enroll, I chose:
      I want to edit someone's profile.
       Agent said: tell whose profile
      but there are no people in the UM and the agent provides no list of things to do.  Need to fix.

**Comment by mbehrooz** [comment]
Fixed, I added a clarifying state which says there are no friends to show after you do you can edit them here and I also removed the user HIMSELF/HERSELF from that list (there is a separate options for editing user himself)
