### ISSUE TITLE
Enroll:  adding people bug

### ISSUE THREAD

**Issue by candysidner** [always-on/always#153]
After adding a person who had a DOB, SKYPE name and phone no, I added a person who did not have these.  What appeared in the final description of the second person was the other person's DOB, SKYPE name and phone no.  Looks like some variables are not getting reset when the next person is added.

**Comment by mbehrooz** [comment]
There was a bug and I fixed the issue, but please generally keep in mind that if you use a repeated name that is already in the owl, other previously added info are going to be shown too. But I realize this was not the case now.
