### ISSUE TITLE
Fix Reeti broken servo

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#160]
on lower lip.  Waiting for part from France.

**Comment by mshayganfar** [comment]
I've done this and there was a problem in loading modules by Reeti. I've put a new post on Reeti's forum and asked Christophe to reply.

**Comment by mshayganfar** [comment]
Reeti's working now, including the bottom lip.

**Comment by candysidner** [comment]
GReat.  I have a question.  What does Reeti look like if he smiles and talks at the same time?

Candy
On Jan 13, 2014, at 6:39 PM, mshayganfar notifications@github.com wrote:

> Reeti's working now, including the bottom lip.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Candace L. Sidner, Ph.D.
Research Professor
Department of Computer Science
Worcester Polytechnic Institute
(508) 831-6637
http://candysidner.com
sidner@wpi.edu
