### ISSUE TITLE
Tilt eyes for Reeti thinking position

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#161]
About the tracking with Karen (or whatever her name is!):  the only thing that doesn't look good is the looking up movement. I think Karen does this as a way to indicate when she is thinking (up left or up right).  Reeti does it at least once where the delay isn't a problem (perhaps because Karen takes so long in the looking up position).  In that case, what I see is that  he needs to move his eyeballs further up (if you look closely Karen does this too).

**Comment by mshayganfar** [comment]
If you think moving eye balls the video looks good, we can close this issue.

**Comment by mshayganfar** [comment]
This issue can be closed now.
