### ISSUE TITLE
Karen's Smile = The Joker?

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#163]
Hi Lazlo, I finally realized why I find Karen's smile slightly creepy.   Please compare her smile attached with The Joker (from Batman).   I think it is the sharp corners of her smile that are the problem.  Perhaps you could round them to make them more feminine?
![joker](https://f.cloud.github.com/assets/2828816/1674835/64729f16-5cff-11e3-9c22-6ded227ebb70.jpeg)
![karen](https://f.cloud.github.com/assets/2828816/1674836/6474beea-5cff-11e3-8972-3cadf0172830.png)

**Comment by candysidner** [comment]
When Karen smiles while talking, this is not a problem because some much of her mouth is devoted to talking.  I think we can set this aside.
