### ISSUE TITLE
Agent comments when user makes invalid GUI action

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#167]
When it is my turn and I try unsuccessfully to move a grey checker, then agent makes a comment.

Btw, the agent should say at the start the red checkers are hers and the grey mine.

**Comment by mbehrooz** [comment]
If it is what I think it is, then it's an intentional feature! It basically says I understand more than you think, do not try to move my stuff... And also try doing that more than 3 times. If it is agent's turn, to be less confusing, the whole board is locked.

**Comment by charlesrich** [comment]
Yes, it did say "don't move my stuff" once (which is sort of obscure), but
then it fell back into it's usual comments.  I think this is a confusing
feature.

-CR

On Fri, Dec 6, 2013 at 10:59 PM, mbehrooz notifications@github.com wrote:

> If it is what I think it is, then it's an intentional feature! It
> basically says I understand more than you think, do not try to move my
> stuff... And also try doing that more than 3 times. If it is agent's turn,
> to be less confusing, the whole board is locked.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/always-on/always/issues/167#issuecomment-30033250
> .

## 

Dr. Charles Rich, Professor, Computer Science Departmenthttp://www.cs.wpi.edu
Interactive Media and Game Development
Programhttp://www.wpi.edu/academics/imgd/
Robotics Engineering Program http://www.wpi.edu/academics/robotics/
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

**Comment by mbehrooz** [comment]
I will change the wording and double check its functionality then. Thanks.

**Comment by mbehrooz** [comment]
I changed the wording for it. The feature is still there but it should be a positive impact now. Feel free to tell me to remove it. Thanks.

**Comment by charlesrich** [comment]
Ok, I kind of like your humor here (for a change!).   

Let's see what Candy thinks...
