### ISSUE TITLE
Ending games smoothly

### ISSUE THREAD

**Issue by candysidner** [always-on/always#172]
At the end of checkers and TTT, when the agent asks if you want to play again and you answer with "not really" it just keeps re-asking the question instead of ending the game with some nice closing comments (for example, Great playing with you! Let's play again sometime).  You can stop the game with the Stop playing button, but that's not a smooth way to end things. 

This may also be true in rummy but I did not test.

**Comment by mbehrooz** [comment]
Pull request for fix added, thanks a lot for noticing it.
