### ISSUE TITLE
lack of go-on or uh-huh in Funny stories;  what did you say does wrong thing

### ISSUE THREAD

**Issue by candysidner** [always-on/always#173]
The app for the agent telling a funny story has no button for "go-on" "uh-huh" or "continue" as the agent tells the story. If you click on "what did you say" which is automatically generated by DiscoRT, it goes on, when it should repeat the last thing said.

**Comment by charlesrich** [comment]
Candy verify?

**Comment by candysidner** [comment]
I tested funny story.  There is now a button to say stop telling the story and I think the agent tells a story well just by pausing and then continuing.  So I am going to close this issue.
