### ISSUE TITLE
EnrollSchemaException thrown at end of log (reproducible)

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#184]
New focus: edu.wpi.always.enroll.schema.EnrollSchema@69205667
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"speech","msg_body":{"text":"I'm ready for you to tell me about your family and friends"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":["Sounds good","Not now, maybe later","I want to edit my own information","I want to edit someone else's information","What did you say?"],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Sounds good\",\r\n  \"Not now, maybe later\",\r\n  \"I want to edit my own information\",\r\n  \"I want to edit someone else's information\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Sounds good"}}
Sent {"msg_type":"stop_speech","msg_body":{}}
Sent {"msg_type":"speech","msg_body":{"text":"Good. Let's start"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Good. Let's start"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes, let's start\",\r\n  \"No, I changed my mind\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes, let's start\",\r\n  \"No, I changed my mind\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Good. Let's start"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Yes, let's start"}}
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"keyboard","instance_reuse_mode":"Remove","params":{"contextMessage":"Enter name:","isNumeric":false}}}
Sent {"msg_type":"speech","msg_body":{"text":"Tell me the person's name. Let me know when you're done"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I'm Done\",\r\n  \"Never Mind\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Tell me the person's name. Let me know when you're done"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I'm Done\",\r\n  \"Never Mind\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"F","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"Fr","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"Fri","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"Frid","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"Frida","isOverflow":false}}
Received {"msg_type":"menu_selected","msg_body":{"text":"I'm Done"}}
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"keyboard","instance_reuse_mode":"Remove","params":{"contextMessage":"Enter Frida's age:","isNumeric":true}}}
Sent {"msg_type":"speech","msg_body":{"text":"Can you tell me Frida's age. Let me know when you're done"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I'm Done\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"8","isOverflow":false}}
Received {"msg_type":"menu_selected","msg_body":{"text":"I'm Done"}}
Sent {"msg_type":"show_-- 1 more
Sent {"msg_type":"hide_plugin","msg_body":{}}
Sent {"msg_type":"stop_speech","msg_body":{}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Sent {"msg_type":"speech","msg_body":{"text":"Do you want to tell Frida's birthday ?"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Do you want to tell Frida's birthday ?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":["Yes","No","Never Mind","What did you say?"],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Never Mind\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Never Mind\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Do you want to tell Frida's birthday ?"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Yes"}}
Sent {"msg_type":"show_-- 1 more
Sent {"msg_type":"speech","msg_body":{"text":"What is Frida's birthday month ?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"January\",\r\n  \"February\",\r\n  \"March\",\r\n  \"April\",\r\n  \"May\",\r\n  \"June\",\r\n  \"July\",\r\n  \"August\",\r\n  \"September\",\r\n  \"October\",\r\n  \"November\",\r\n  \"December\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"What is Frida's birthday month ?"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"December"}}
Sent {"msg_type":"show_-- 1 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"keyboard","instance_reuse_mode":"Remove","params":{"contextMessage":"Enter Frida's Birthday:","isNumeric":true}}}
Sent {"msg_type":"speech","msg_body":{"text":"What is Frida's day of Birthday ? . Let me know when you're done"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I'm Done\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"1","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"10","isOverflow":false}}
Received {"msg_type":"menu_selected","msg_body":{"text":"I'm Done"}}
Sent {"msg_type":"show_-- 1 more
Sent {"msg_type":"hide_plugin","msg_body":{}}
Sent {"msg_type":"stop_speech","msg_body":{}}
Sent {"msg_type":"speech","msg_body":{"text":"May I ask Frida's gender ?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"May I ask Frida's gender ?"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Male\",\r\n  \"Female\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Male\",\r\n  \"Female\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"May I ask Frida's gender ?"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Female"}}
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"speech","msg_body":{"text":"Do you happen to know Frida's ZipCode ?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Do you happen to know Frida's ZipCode ?"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Yes"}}
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"keyboard","instance_reuse_mode":"Remove","params":{"contextMessage":"Enter Frida's zipcode:","isNumeric":true}}}
Sent {"msg_type":"speech","msg_body":{"text":"Please tell me Frida's zipcode ?. Let me know when you're done"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I'm Done\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"0","isOverflow":false}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Please tell me Frida's zipcode ?. Let me know when you're done"}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"03","isOverflow":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I'm Done\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"034","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"0346","isOverflow":false}}
Received {"msg_type":"keyboard.textUpdate","msg_body":{"text":"03468","isOverflow":false}}
Received {"msg_type":"menu_selected","msg_body":{"text":"I'm Done"}}
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"hide_plugin","msg_body":{}}
Sent {"msg_type":"speech","msg_body":{"text":"What is your relationship with Frida? For example, is this person your cousin or your friend?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Friend\",\r\n  \"Sister\",\r\n  \"Brother\",\r\n  \"Mother\",\r\n  \"Father\",\r\n  \"Daughter\",\r\n  \"Son\",\r\n  \"Granddaughter\",\r\n  \"Grandson\",\r\n  \"Aunt\",\r\n  \"Uncle\",\r\n  \"Cousin\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Granddaughter"}}
Sent {"msg_type":"show_-- 1 more
Sent {"msg_type":"stop_speech","msg_body":{}}
Sent {"msg_type":"speech","msg_body":{"text":"Is Frida married?"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Is Frida married?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Is Frida married?"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"No"}}
Sent {"msg_type":"show_-- 2 more
Sent {"msg_type":"speech","msg_body":{"text":"Do you plan to talk to this person by SKYPE video calls ?"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[]"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Yes\",\r\n  \"No\",\r\n  \"Never Mind\",\r\n  \"Skip Frida\",\r\n  \"What did you say?\"\r\n]"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Do you plan to talk to this person by SKYPE video calls ?"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"No"}}
Disposing of edu.wpi.always.enroll.schema.EnrollSchema@69205667...
Disposing of edu.wpi.always.cm.schemas.SessionSchema@de548a2...Exception in thread "edu.wpi.always.cm.schemas.SessionSchema" Exception in thread "edu.wpi.always.enroll.schema.EnrollSchema
Received {"msg_type":"done","msg_body":{"action":"show_menu","dException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchema
Received {"msg_type":"done","msg_body":{"action":"show_menu","dException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchema
Received {"msg_type":"done","msg_body":{"action":"show_menu","dException in thread "edu.wpi.always.enroll.schema.EnrollSchema
Received {"msg_type":"done","msg_body":{"action":"show_menu","dException in thread "edu.wpi.always.enroll.schema.EnrollSchemaException in thread "edu.wpi.always.enroll.schema.EnrollSchema
Received {"msg_type":"done","msg_body":{"action":"show_menu","dException in thread "edu.wpi.always.enroll.schema.EnrollSchema

**Comment by mbehrooz** [comment]
Thanks for pointing this out. I tried to recreate this but no where I get an exception or crash. Is this only apparent in logs (it is marked crash)?

**Comment by mbehrooz** [comment]
I ran the exact inputs twice with variable timings and I did not get any exception or abnormal behavior at least as far as the experience and Console log goes. I will keep an eye on this when I am working on Enroll.

**Comment by candysidner** [comment]
Morteza, this may only occur if you run the full agent with all of the system loaded.  I always run plugins as part of Always-Stranger, Always-Acquaintance or Always-Companion.  If you are running just the plugin and don't see this, try running Alway-Stranger.  If it shows up there, then we have some very interesting difference!

**Comment by charlesrich** [comment]
@mbehrooz

**Comment by charlesrich** [comment]
This undoubtedly has to do with which User.owl you are starting with.   Candy, was this with _no_ User.owl or the default from the repository?

**Comment by mbehrooz** [comment]
@charlesrich It most definitely did! Although I was getting emails before too, it might be because I have set my watching status for always to "Not watching" rather than ignore, which would email you if there is a new comment in a thread you have participated in before. But @ feature is of course much more useful.

**Comment by mbehrooz** [comment]
I agree that it could have been User.owl settings.
