### ISSUE TITLE
calendar bug, two events when change in time

### ISSUE THREAD

**Issue by candysidner** [always-on/always#191]
The calendar bug came about when I tried to change an event.  It changed the time as I requested, but displayed the event on two successive days.  When I asked to delete the event, both were deleted.

You will find a run at: https://www.dropbox.com/s/9pz25ta7qqsvwz5/Consolewdoubleentry.test
that has an example of this bug.

**Comment by mbehrooz** [comment]
If I remember this correctly, when I looked at the logs, it was obvious that it happened because the event's length was more than the remaining time in that date and it overflowed. So it actually makes sense to be this way.

**Comment by charlesrich** [comment]
That is fine as long as it doesn't cause a crash.  Please test to confirm.

**Comment by mbehrooz** [comment]
I tested to edit all associated data, no crash occurs. Thanks.
