### ISSUE TITLE
rummy seemed to die after I won the game

### ISSUE THREAD

**Issue by candysidner** [always-on/always#192]
I htink this bug is in Rummy but maybe it's elsewhere.  Look in the console.test file https://www.dropbox.com/s/ugsp93jszj10cus/Issue192.test  You will find the rummy part which I finally had to stop.  I did that because the agent was just thinking for a long time.  The agent went into thinking mode after I won the game, wchih is not reflected anywhere in the printout from the run.

Thereafter I did other activities, but the head stayed up and to the right.

**Comment by mbehrooz** [comment]
Resolved, thanks a lot.
