### ISSUE TITLE
how is user doing?

### ISSUE THREAD

**Issue by candysidner** [always-on/always#193]
In About if there are no other friends, the agent asks how is User doing?  This is kind of dumb.  There needs to be some check in the code for this. 

The fix (if not already done) is to call the version of getPersons() method with flag to omit user.

**Comment by mbehrooz** [comment]
Inside the About.d4g there is the getPeople(false) call. So the user herself is not included. Is this already fixed or maybe I do not understand the issue description above...

**Comment by charlesrich** [comment]
I don't know if it is already fixed.  Please confirm.

**Comment by mbehrooz** [comment]
Can you please tell me how to run the About? It does not come up as a list of activity I can do, I think, or I don't recognize it. What is it's keyword? Thanks.

**Comment by mbehrooz** [comment]
So because the About is offered only if there are friends, and also the hinted line of code is fixed. I also tested all these nowhere it says "User" or call user name when it shouldn't

Therefore, this issue is resolved as well. Thank you.
