### ISSUE TITLE
"What did you say?" not working well with games

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#195]
Clicking on What did you say? for TTT (and probably other games) gives odd behavior.  

See use of REPEAT in AdjacencyPairBase for logic to see if games are violating expectations of this code somehow?

Btw, it is ok (in fact desirable, I think) if this option does not appear if there is no menu, even if the agent just said something (but there are no possible replies).   Mostly this is to facilitate user choosing from answer menu.

**Comment by mbehrooz** [comment]
I removed it from games except for the tutorial. Thanks.

**Comment by mbehrooz** [comment]
It think this should be resolved.
