### ISSUE TITLE
Calendar touch event

### ISSUE THREAD

**Issue by candysidner** [always-on/always#199]
This is a small enhancement if you have time:  when you touch an event on the calendar (for changing or deleting it), it doesn't turn blue (like everything else).  Makes it hard to tell if you actually touched it correctly.

I assume this is a calendar only problem but maybe it is not

**Comment by mbehrooz** [comment]
Considering the time constrains I would leave this out if you would agree.

**Comment by charlesrich** [comment]
Let's not close it yet.  It sounds like a real source of confusion.

**Comment by mbehrooz** [comment]
I don't know, to me it's perfectly clear, here's what happens in deleting events, after you pick the week all events (noticeably) turn to buttons. Then you push one and it will delete that (or brings up menus to change that...)

**Comment by charlesrich** [comment]
Fine. If you think it is clear, I am closing the issue.
