### ISSUE TITLE
additions to dialog for rummy (both regular play and tutorials)

### ISSUE THREAD

**Issue by candysidner** [always-on/always#209]
I"m most concerned for Always-On with the least competitive levels (.1 and .2).  But obviously you want to show that the library has responses for the other levels of competition.  I don't know what the critical points are in rummy other that when one melds.  But I think it might be good to do the following:
0.  For melds, the comments should be positive, for example:  good job getting a meld, or  I didn't expect you to meld yet!
1. at the beginning have either agent be able to ask "how is your hand?" with some comments like "it's okay" or "it's terrible" or "I'm not telling you!" 
2. If the user discards and the agent takes the discard, that seems to be a point to have something like "thanks! I wanted that card" and vice versa for the agent discarding and the human take up.  
3. comments when one of the two wins, 
4.when either player gets down to a small number of cards (like 3).  Soemthing like "I'm getting close to winning" or for observing the other player's hand: you only have a few cards left!  
5.  If you can think of other points, add them.

Last thing, rummy needs a tutorial, which should not be for levels of competitiveness.  There are no tutorials for TTT or checkers. The tutorial should be something like this:

Before we start, do you want a refresher on playing rummy?
yes definitely
no I don't need it

for yes, the agent proceeds:
To win in rummy you must empty your hand of cards before I do.
 human: go on
To empty your hand, You place cards from your hand on the table by making a meld.
human: go on
A meld is 3 cards of the same type.  For example all nines.  A meld is also 3 cards in sequence in the same suit.  Like the 9, 10 and 11 of hearts.
human: go on
Your turn starts when you take a card from the deck or the discard pile.
human: uh-huh
If you want to meld, you meld during your turn before you discard. 
human: ok
During your turn you can also add to a meld on the table.  The meld can be your own or mine!
human: ok
It's a bit tricky to get cards to sit on the table as a meld.  If it doesn't work the first time, just move the card around a bit til it sticks.
human:  that's sounds pretty odd.  But I'll try it.
human: Okay, will do.
After you discard a card, it's my turn.  
human: ok
By the way, even though your cards are face up, I can't see them!
human: that's good!
human: I guess I"ll trust you on that.
Okay, let's play!
human: yes, great!
Human: I want to hear the whole explanation one more time.

**Comment by mbehrooz** [comment]
Thanks a lot for designing it, Tutorial is made. I will also add some way/scenario to emphasize the initial comment, e.g. how is your hand, etc.

**Comment by mbehrooz** [comment]
Hi, Numbers 2 and 4 are not there and will be added, but please keep in mind that other ones and some extra ones are there already and they are not active only because there are no comments for them with right tags in the library. As part of my debug, I will do the same I did for checkers to provide a complete library of all situations for rummy and then the editing can be done on them (or to add new ones and remove some, etc.) 
Thank you very much for the great feedback.

**Comment by mbehrooz** [comment]
Added all of them. Thanks.
