### ISSUE TITLE
Show rummy UI during tutorial

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#214]
bring up the rummy display at the _start_ of the tutorial, so people can look at it (but make sure it cannot be clicked on---please test).  And make sure there is no problem with bringing it up again when you start the actual game

**Comment by mbehrooz** [comment]
Added, Thanks.

**Comment by charlesrich** [comment]
Rummy table is empty, which is not much use!   Initialize it with a typical game state (melds on both sides).

Also, explain whose cards are whose.

**Comment by mbehrooz** [comment]
Ok, so the way the VS part works is that in order for me to get the "who to play first" feature, I had to postpone initialization until I actually know who is going to play first. One quick fix could be to ask that question before tutorial, which is not that odd, I think.

**Comment by mbehrooz** [comment]
Another solution could be to initialize the board at the tutorial time, but initializing it again when actually starting to play, which in that case cards would be refreshed and player sees his/her hand changed after tutorial. To reduce this, I could also go for guessing (a default first player) and only if that changes by user choice, then the cards will get refreshed. Counting this as solution 2, I think the first solution (in previous comment) makes more sense. @charlesrich

**Comment by mbehrooz** [comment]
Solved.
