### ISSUE TITLE
2 small bugs in Calendar

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#220]
Birthdays should not have start times and duration.  I imagine you could set this up in OWL, but it might be easier just to amend the code.  

Also reminders can have start times, but no lengths.

Since this turns out to require changes in the OWL structures, so I've decided to treat this as an enhancement if and when someone has time to deal with it.

**Comment by mbehrooz** [comment]
If I am not mistaken, duration and start time in Ontology events cannot be null. I will look into changing it to see if there could be used another type of Ontology event perhaps but as I tried it and as it is it must have a value to save (or a default one which user does not put into system and we do, for example all birthdays start at 00:00 AM for one day duration, which is kind of what Facebook and Google do and it makes sense too, if this makes sense, please tell me to do it.) Thanks.

**Comment by charlesrich** [comment]
@mbehrooz let's not mess with the ontology at this point.   I wonder what Will's original design intention for birthdays was?   Please investigate.

If you make them all day, then they will overlap with other events for that day, and how will that display?   HOW DO overlapping events display???

How about just automatically making a short (1/2 hour entry) at some reasonable time, like 10am.  

This is not a product.

**Comment by mbehrooz** [comment]
I made the changes and sent a pull request. (birthday being a 30 minutes event from 10 AM  and reminders having a length of 1 minute for both single and repeating events). So this issue is resolved. Thanks.

**Comment by mbehrooz** [comment]
This is now resolved.
