### ISSUE TITLE
Fix Warning in Visual Studio

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#224]
Warning 1   'System.Net.Dns.Resolve(string)' is obsolete: 'Resolve is obsoleted for this type, please use GetHostEntry instead. http://go.microsoft.com/fwlink/?linkid=14202'   C:\Users\rich\Documents\GitHub\always\core\Client\Client.UI\ReetiCommunication.cs   63  42  Client.UI

**Comment by mshayganfar** [comment]
This has been fixed and you merged my pull request.
