### ISSUE TITLE
crash during checkers

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#228]
Note sure if this is a chckers or agent bug.
See dump file:  https://www.dropbox.com/s/geta16fsbqs29sj/CheckersCrash.test

**Comment by mbehrooz** [comment]
Hi, thanks for the report but the link does not work.

**Comment by charlesrich** [comment]
@mbehrooz Candy fixed the link

**Comment by charlesrich** [comment]
Closing since study ok.
