### ISSUE TITLE
Crash in repeating event for Calendar

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#229]
App dies when trying to set up a repeating event addition to the calendar.

The crash point is near the end of the dump file.  
Dump file at:  https://www.dropbox.com/s/visqie8wjm0vs65/CalendarCrash.test

**Comment by mbehrooz** [comment]
The report link is broken, I will look into it still if you do not have it, but saying just in case you do. Morteza.

**Comment by charlesrich** [comment]
@mbehrooz I think Candy fixed the link

**Comment by mbehrooz** [comment]
This seems to be fixed same as #238 !
