### ISSUE TITLE
TicTacToe Crash

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#236]
The game crashed after I played it through once; It was a tie so we played again. The crash happened when I would ask her "What did you just say?" I was asking her this because it was an option even if she didn't previously say anything.

**Comment by raggroupkathleen** [comment]
Here is the preceding code..

Sent {"msg_type":"tictactoe.agent_cell","msg_body":{"cellNum":8}}
Sent {"msg_type":"ticta-- 1 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"start-- 1 more
Sent {"msg_type":"speech","msg_body":{"text":""}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":""}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"0.0","horizontal":"0.0"}}
Sent {"msg_type":"speech","msg_body":{"text":" I am in this to win "}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":" I am in this to win "}}
Sent {"msg_type":"start-- 7 more
Sent {"msg_type":"tictactoe.playability","msg_body":{"value":"true"}}
New focus: edu.wpi.always.ttt.TTTSchema@72169076
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":["I won't let you","It's just a game","Well do your best","What did you say?"],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I won't let you\",\r\n  \"It's just a game\",\r\n  \"Well do your best\",\r\n  \"What did you say?\",\r\n  \"Stop playing TicTacToe\"\r\n]"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"It's just a game"}}
Sent {"msg_type":"start-- 68 more
Sent {"msg_type":"tictactoe.playability","msg_body":{"value":"true"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"gaze","msg_body":{"vertical":"-1.0","horizontal":"-1.00125"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Stop playing TicTacToe\"\r\n]"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"tictactoe.human_played_cell","msg_body":{"cellNum":6}}
Sent {"msg_type":"start-- 81 more
Sent {"msg_type":"tictactoe.playability","msg_body":{"value":"false"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"tictactoe.playability","msg_body":{"value":"false"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
New focus: edu.wpi.always.ttt.TTTSchema@72169076
Sent {"msg_type":"show_menu","msg_body":{"menus":["Now did you see that?","I like playing with you","Your turn","What did you say?"],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Now did you see that?\",\r\n  \"I like playing with you\",\r\n  \"Your turn\",\r\n  \"What did you say?\",\r\n  \"Stop playing TicTacToe\"\r\n]"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"What did you say?"}}
Sent {"msg_type":"start-- 6 more
Sent {"msg_type":"tictactoe.playability","msg_body":{"value":"false"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"tictactoe","instance_reuse_mode":"Reuse"}}

**Comment by charlesrich** [comment]
@mbehrooz

**Comment by mbehrooz** [comment]
Thanks a lot for reporting this, although I think this is the "what did you say bug which already has an issue" in the list and is not related to any specific games.
