### ISSUE TITLE
Checkers Crashed at End of Game

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#237]
After winning a game of checkers, the agent crashed and I was able to move my pieces anywhere on the board (in black squares). Here is some of the code...

Sent {"msg_type":"checkers.confirm_human_move","msg_body":{"human_move":"confirmed"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"checkers.human_played_move","msg_body":{"humanMove":"7,4//6,3"}}
Sent {"msg_type":"checkers.confirm_human_move","msg_body":{"human_move":"confirmed"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"checkers.human_played_move","msg_body":{"humanMove":"6,3//7,2"}}
Sent {"msg_type":"start-- 1 more
Sent {"msg_type":"checkers.confirm_human_move","msg_body":{"human_move":"confirmed"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"checkers.human_played_move","msg_body":{"humanMove":"7,2//6,1"}}
Sent {"msg_type":"start-- 5 more
Sent {"msg_type":"checkers.confirm_human_move","msg_body":{"human_move":"confirmed"}}
Sent {"msg_type":"check-- 1 more
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Your turn"}}
Sent {"msg_type":"start-- 4 more
Sent {"msg_type":"checkers.playability","msg_body":{"value":"false"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":["I finally win. Good game","Did you see that?  I won!","Anyway","What did you say?"],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"I finally win. Good game\",\r\n  \"Did you see that?  I won!\",\r\n  \"Anyway\",\r\n  \"What did you say?\",\r\n  \"Stop playing checkers\"\r\n]"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"What did you say?"}}
Sent {"msg_type":"start-- 29 more
Sent {"msg_type":"checkers.playability","msg_body":{"value":"false"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"checkers","instance_reuse_mode":"Reuse"}}

**Comment by charlesrich** [comment]
referring this to @mbehrooz

**Comment by mbehrooz** [comment]
Thanks for reporting. Here again the problem is 
Received {"msg_type":"menu_selected","msg_body":{"text":"What did you say?"}}
Which causes crash currently and is not part of any game. Please do not use "What did you say" in any game, it is an underlying bug between games and system core.
