### ISSUE TITLE
Calendar Frozen after Repeat Event

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#238]
I wanted an event in the calendar 9:00am, religious event every Sunday. The agent says it may take a minute and she froze. 

Sent {"msg_type":"show_menu","msg_body":{"menus":["Home","Work","Somewhere else","What did you say?"],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Home\",\r\n  \"Work\",\r\n  \"Somewhere else\",\r\n  \"What did you say?\",\r\n  \"Stop using the calendar\"\r\n]"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"calendar","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Where is the event taking place"}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Home\",\r\n  \"Work\",\r\n  \"Somewhere else\",\r\n  \"What did you say?\",\r\n  \"Stop using the calendar\"\r\n]"}}
Sent {"msg_type":"start-- 2 more
Sent {"msg_type":"show_menu","msg_body":{"menus":["Home","Work","Somewhere else","What did you say?"],"twoColumn":false,"extension":false}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"calendar","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"menu_selected","msg_body":{"text":"Somewhere else"}}
Sent {"msg_type":"start-- 3 more
Sent {"msg_type":"speech","msg_body":{"text":"Okay, give me a moment to set up your repeating event"}}
Sent {"msg_type":"show_menu","msg_body":{"menus":[],"twoColumn":false,"extension":false}}
Received {"msg_type":"done","msg_body":{"action":"show_menu","data":"[\r\n  \"Stop using the calendar\"\r\n]"}}
Sent {"msg_type":"start_plugin","msg_body":{"name":"calendar","instance_reuse_mode":"Reuse"}}
Received {"msg_type":"done","msg_body":{"action":"speech","data":"Okay, give me a moment to set up your repeating event"}}32624426-6b6b-458b-b6db-53ef6093dd82 - 2014-02-02 - 2014-03-16 - 09:00:00.000 - PT1H - WEEKLY
32624426-6b6b-458b-b6db-53ef6093dd82 - 2014-02-02 - 2014-03-16 - 09:00:00.000 - PT1H - WEEKLY
32624426-6b6b-458b-b6db-53ef6093dd82 - 2014-02-02 - 2014-03-16 - 09:00:00.000 - PT1H - WEEKLY
32624426-6b6b-458b-b6db-53ef6093dd82 - 2014-02-02 - 2014-03-16 - 09:00:00.000 - PT1H - WEEKLY
32624426-6b6b-458b-b6db-53ef6093dd82 - 2014-02-02 - 2014-03-16 - 09:00:00.000 - PT1H - WEEKLY
32624426-6b6b-458b-b6db-53ef6093dd82 - 2014-02-02 - 2014-03-16 - 09:00:00.000 - PT1H - WEEKLY

**Comment by charlesrich** [comment]
Referring this to @mbehrooz as I think he is working on this bug.

**Comment by mbehrooz** [comment]
I think this is the same as 229, but I will look into it.

**Comment by mbehrooz** [comment]
I tested the calendar with repeating events multiple times and tried to recreate the errors. I remember I myself encountered a bug there but now it seems to be fine. I do not remember that I fixed it but it is possible or maybe someone else fixed it. In any case, it seems perfectly fine now.
