### ISSUE TITLE
Checkers Multiple Moves on Turn

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#241]
In checkers, if you move your pieces fast enough you can move all of them before the agent has a turn to go.

**Comment by charlesrich** [comment]
@mbehrooz

**Comment by mbehrooz** [comment]
Ok, I see how that can happen and I have a easy fix for it. Thanks a lot for reporting this, smart bug!

**Comment by mbehrooz** [comment]
Solved, thank you.

**Comment by mbehrooz** [comment]
Same issue existed with TTT and is now solved.
