### ISSUE TITLE
Rummy Crash at End

### ISSUE THREAD

**Issue by raggroupkathleen** [always-on/always#251]
After I won the game, the agent didn't say anything but I still had the option to ask, "what did you say?" Then she crashed. Issue in drive.

**Comment by charlesrich** [comment]
@raggroupkathleen 

@mbehrooz, I think this is fixed, but just in case it is a boundary condition, could you please check.

The log file is here: https://www.dropbox.com/s/7uakqbqc0l29cpd/Rummy%20Crash.test

**Comment by mbehrooz** [comment]
Ok thanks for reporting this, so I just checked the rummy in all cases of starting the game and this is not  happening. I am confident that this must have been caused by the bug we solved few days ago.
