### ISSUE TITLE
Karen disappears in Exercise

### ISSUE THREAD

**Issue by candysidner** [always-on/always#257]
Karen gave a test message and then left the screen when I tried to use nutrition advice.  I started iwth an empty user model, added to it during the run and it had no errors.
Test file below.  I added ***HERE"S THE ERROR POINT where the error occurred:
https://www.dropbox.com/s/klmwtgitvxk6dsd/KarendisappearsFeb6.test

**Comment by candysidner** [comment]
Here is what the screen looked like at the time of the error:
https://www.dropbox.com/s/jr73zkt1nlwmepx/karendisappears.png

**Comment by charlesrich** [comment]
@lring

**Comment by zessie** [comment]
The new version includes fixes for this bug.
