### ISSUE TITLE
Null pointer exception--nutrition or task switching?

### ISSUE THREAD

**Issue by candysidner** [always-on/always#258]
this happens when I asked the agent to do nutrition (and then also for other things).  it may be a boundary error in the Agent or it may be in nutrition.  
Note this run was done with an empty Owl user model to which I added things.  It ran correctly on calendar, enroll, talkabout.
Test file:https://www.dropbox.com/s/z0by9dzc0pczcqn/ExceptionFeb6.test

**Comment by charlesrich** [comment]
@lring, this looks like same error as #256 

What? How are choices empty here?
Exception thrown:java.lang.NullPointerException
