### ISSUE TITLE
Your Turn appears incorrectly

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#266]
@mbehrooz I saw this bug in TTT, but it may exist in other apps.  Agent had first turn (X), which means that it is my turn.  But as you can see in screen shot, "Your turn" is one of the options, I think this is a logical bug.

https://www.dropbox.com/s/xbmh76grvit2egy/TTT-YourTurn.rtf

**Comment by mbehrooz** [comment]
I took a look and the bug is caused simply by a reply option in library. I also doubled checked the code and it is right. The buggy comment is the second one in the TTT library. Basically in library there should not be a your turn, because I am adding it when necessary/right. I will send a pull.

**Comment by charlesrich** [comment]
Great.  Please check the other games for similar error.

**Comment by mbehrooz** [comment]
Also (unrelated to this), The library for TTT is fairly small, making the comments choices just a few ones for human mostly, I will try to expand that as soon as I get some time too.

Thanks for noticing this.

**Comment by mbehrooz** [comment]
Exactly, I just wanted to say I will check it for other games! Thanks.

**Comment by charlesrich** [comment]
Improving TTT comments is not a priority, except that it makes a great quick demo of the concepts, which we all will find useful...

**Comment by mbehrooz** [comment]
Definitely, I agree. As a small point, an elaborated version of "Your turn" can logically truly be added if the "madeOn" property of comments is used accordingly. Something like "I know, but it is your turn now!"
