### ISSUE TITLE
New Rummy Freeze at start of game

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#273]
@mbehrooz the agent froze looking at cards at start of game (her turn) with no menu in following (running plugin standalone):

https://www.dropbox.com/s/9o83cip48z249y0/RummyFreezeFeb7.txt

**Comment by mbehrooz** [comment]
The same thing happened to me yesterday as a result of not building the VS. And I just ran it several times and this is not happening. Is that a possibility do you think?
