### ISSUE TITLE
Failures of NEU plugins to run after sucessfully running Humorous Stories

### ISSUE THREAD

**Issue by candysidner** [always-on/always#283]
@lring @zessiez Because I used an empty user model and after doing the initial UM with the agent, I skipped through to try to run the NEU plugins.  After running Humorous Stories completely (til it ran out of a script), I tried others of the NEU plugins.  The overall system gave each one focus and then took it away.  
https://www.dropbox.com/s/x9jmypmapa7qyrt/FailuresNEUPluginsDontRun.test
This run also contains an error at the end for trying to add a birthday to the calendar, but I will see if I can repeat that bug as it may be due to all the other probelms.

**Comment by charlesrich** [comment]
The IllegalThreadStateException has been fixed.
Leaving Calendar bug to be checked by Morteza.  =CR
