### ISSUE TITLE
Connecting Reeti's to PC's without CS network

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#294]
@mshayganfar, we need to figure out the easiest way to connect the Reeti PC to the HP PC directly without relying on the CS network.  Please do some online research about the options, such as a cross-over cable, special-purpose box, or a cheap router.

Report on the options and we will order some.

**Comment by charlesrich** [comment]
@mshayganfar

b. Connect the PC to the local router through the WIFI connection (all participants will already have WiFi).
c. Connect Reeti to the PC using a network cross cable.
d. Configure PC as a gateway for the Reeti to have remote access to the Reeti. (nice, but not necessary; if there is a problem with Reeti, it is most likely to be hardware and will require in-person visit).
e. Configure IP addresses of the PC and the Reeti according to the IP range at the house.

**Comment by mshayganfar** [comment]
This task is done.
