### ISSUE TITLE
AnecdotesSchema starts Nutrition

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#296]
@lring @zessiez When I selected "Hear Funny Stories" (AnecdotesSchema) from main menu, the first thing the agent said was "Do you want to hear a nutrition tip?"

This could be due to something in user model, but until Issue #276 is addressed, that information will not be automatically printed out in log at start of session.

-CR

**Comment by zessie** [comment]
The funny stories include a bunch of tips and the nutrition tip is one of them.

**Comment by charlesrich** [comment]
Ok, I'll change the title in the menu.
