### ISSUE TITLE
Image display plugins (e.g., Nutrition) not showing agent

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#318]
@lring @candysidner @zessiez

In Nutrition (and perhaps other scriptbuilder plugins that display images?), when the image is being shown, it simply replaces the agent, rather than switching into the mode in which a smaller agent is on the side above the menus.  So the agent is talking, but we can't see her.

It looks like you could simply add this function to the 'page' command?  And then return to the normal mode in the ?idle? command?

Finally, before closing this issue, please confirm that in Reeti mode, the agent is _not_ visible.

**Comment by zessie** [comment]
When showing images, the agent will disappear from the sceen. This is how we have implemented it so far.

**Comment by charlesrich** [comment]
@lring @candysidner 

Yes, I agree this is a design issue--I have changed label from bug to enhancement.   However, having the agent appear in reduced size above the menu buttons would be consistent with all the other plugins (calendar, games, story, etc.) that also display images.   If this is very easy to do (which I think it might be) please consider whether it would be a better design.  -CR
