### ISSUE TITLE
Reeti ear-wiggle

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#325]
@mshayganfar

To signal going from Idle to Attention (due to motion or face), it would be nice to have a simple little ear-wiggle command I can send.  

I added a stub for wiggle to ReetiCommandSocket.

**Comment by mshayganfar** [comment]
This task is done.

**Comment by charlesrich** [comment]
Thanks.  Can you please send me a quick video to look at?

Also, before closing the issue, we need to test the code "in situ" by
seeing how it works in the engagement state machine---I need to add some
calls to it, which I will do ASAP (I am slowed down with another bad cold
this weekend :-(

-CR

On Fri, May 2, 2014 at 8:52 PM, Mohammad Shayganfar <
notifications@github.com> wrote:

> This task is done.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/always-on/always/issues/325#issuecomment-42065214
> .

## 

Dr. Charles Rich, Professor, Computer Science Departmenthttp://www.cs.wpi.edu
Interactive Media and Game Development
Programhttp://www.wpi.edu/academics/imgd/
Robotics Engineering Program http://www.wpi.edu/academics/robotics/
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich
