### ISSUE TITLE
Storage of story videos

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#334]
@lring
Have you thought about where the video files should go?  Putting them in the bin/Debug directory is obviously not the right place.

Maybe in c:\Dropbox<COMPUTERNAME>\video ?

This would have the advantage of providing convenient backup and access, but I am a bit worried about their size.  How big are they?  (We can certainly  buy more space on Dropbox).

**Comment by candysidner** [comment]
Lazlo, Have you done this?  if so, I can close this issue (this is Candy)

**Comment by charlesrich** [comment]
Since the dev envt is not present on study machines, this directory will
not exist.  I suggest just creating videos folder C;/Dropbox/MachineName
and putting them there (see main in weather plugin for example code using
weatherData) No labor to collect and can see when being used.

## Sent from my Droid...

Dr. Charles Rich, Professor, Computer Science Department
Interactive Media and Game Development Program
Robotics Engineering Program
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

**Comment by charlesrich** [comment]
Yes, this is especially important because the 'release' folder (which is the running directory) in Dropbox for study machines will get _overwritten_ when a new release is pushed out.   

-CR

**Comment by lring** [comment]
In the latest push this is fixed.

They will now go to C:\Dropbox\<ComputerName>\

**Comment by charlesrich** [comment]
Tx, Lazlo.  I am sorry to micromanage, but don't you think it would be
better to manage if these videos were in a separate subfolder?

Also, I only took a quick look at the patch, but will two stories of the
same type overwrite each other?

Chuck

## Sent from my Droid...

Dr. Charles Rich, Professor, Computer Science Department
Interactive Media and Game Development Program
Robotics Engineering Program
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

**Comment by charlesrich** [comment]
Hey Chuck,

The files won't override each other since they are suffixed with the time
and date of recording.

I can move it to a separate subfolder if needed however.

--Lazlo

**Comment by charlesrich** [comment]
Great.

A separate folder, as done with weatherData, would really be a good idea.

-CR

On Thu, Jan 15, 2015 at 4:17 PM, Lazlo Ring lring@ccs.neu.edu wrote:

> Hey Chuck,
> 
> The files won't override each other since they are suffixed with the time
> and date of recording.
> 
> I can move it to a separate subfolder if needed however.
> 
> --Lazlo
> 
> On Thu, Jan 15, 2015 at 3:46 PM, Charles Rich rich@wpi.edu wrote:
> 
> > Tx, Lazlo.  I am sorry to micromanage, but don't you think it would be
> > better to manage if these videos were in a separate subfolder?
> > 
> > Also, I only took a quick look at the patch, but will two stories of the
> > same type overwrite each other?
> > 
> > Chuck
> > 
> > ## Sent from my Droid...
> > 
> > Dr. Charles Rich, Professor, Computer Science Department
> > Interactive Media and Game Development Program
> > Robotics Engineering Program
> > Worcester Polytechnic Institute, Fuller Laboratories B25b
> > 100 Institute Road, Worcester, MA 01609-2280
> > 
> > Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
> > Home: http://www.cs.wpi.edu/~rich
> > On Jan 15, 2015 2:21 PM, "lring" notifications@github.com wrote:
> > 
> > > In the latest push this is fixed.
> > > 
> > > They will now go to C:\Dropbox<ComputerName>\
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/always-on/always/issues/334#issuecomment-70144488.

## 

Dr. Charles Rich, Professor, Computer Science Department
http://www.cs.wpi.edu
Interactive Media and Game Development Program
http://www.wpi.edu/academics/imgd/
Robotics Engineering Program http://www.wpi.edu/academics/robotics/
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

**Comment by lring** [comment]
Fixed in latest push
