### ISSUE TITLE
Possible restart problem

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#352]
Yes, I agree that this should not prevent delivery of Reeti's, as long as we keep a _working_ Reeti at the lab.   You can follow up on this after your recovery break :-) later this week.

Overall, my guess is that the code is working and the problem is in testing it properly.  

For example, after the face is lost, Reeti keeps looking in the same direction for three seconds (no sends) before it returns to the neutral position (which requires a send).   However, if it was _in_ the neutral position when it lost the face, there will be no send to return it to the neutral position.  So to get it do a send and then crash, you must get it to reacquire your face and then track it.   (It is fine that it doesn't crash until it actually needs the socket!)

I can easily imagine that not knowing these details, you could not have done the right combination of things to make it need the socket.

Anyways, we can work on this together further later this week.

Thanks for hanging in there, and sorry this ordeal is not yet over.

-Chuck

On Sun, May 11, 2014 at 11:42 PM, Behrooz, Morteza mbehrooz@wpi.edu wrote:
I'm not in the lab now. Will do that later today and will send a pull regardless. If this lingers I will try to work on it on Monday but this is not a reeti code (and the bug is not in the server) so no worries for delivering robots, while I'll try to make this work for tuesday if java bug individually lingers.

On May 11, 2014, at 5:39 PM, "Charles Rich" <rich@WPI.EDU<mailto:rich@WPI.EDU>> wrote:

Temporarily comment out the if part of line 100 and see if that makes any difference.
## Sent from my Droid...

Dr. Charles Rich, Professor, Computer Science Department
Interactive Media and Game Development Program
Robotics Engineering Program
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edumailto:rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

On May 11, 2014 11:36 PM, "Behrooz, Morteza" <mbehrooz@wpi.edu<mailto:mbehrooz@wpi.edu>> wrote:
I did that but it does not seem to crash even when it Should find my face... I am not sure what would the fix be to commit it for pull request.

Yours, M

On May 11, 2014, at 4:21 PM, "Charles Rich" <rich@WPI.EDU<mailto:rich@WPI.EDU>mailto:rich@WPI.EDU<mailto:rich@WPI.EDU>> wrote:

Hi Morteza, Sorry I did not follow up on the details in your email more carefully.  I was rushing out for dinner.  Back now.

Also, the two servers are not very intuitively named (not your fault), so I got them confused.

In any case, you are _correct_ about line 100 in ReetiFaceTrackerRealizer, which prevents the Java client from sending the same message over and over when the face has not moved.  Try getting Reeti to track some movement in your face, which should make it call send, which should make it crash.

Let me know.

-Chuck

On Sun, May 11, 2014 at 9:10 PM, Behrooz, Morteza <mbehrooz@wpi.edu<mailto:mbehrooz@wpi.edu>mailto:mbehrooz@wpi.edu<mailto:mbehrooz@wpi.edu>> wrote:
On the wiggle, I was not sure what the desired outcome is so no nothing is wrong.

The restart video has "wait" in its name. It works.

On Java client bug, this is NOT about C++ or happiness value holder. Face detection server is not ReetiCapturing server and has nothing to do with the C++ client (dll). ReetiCapturing was also not closed in this test.

This is Java client. And please refer to my original email again. I am completely certain that the send is not called and so it raises no exception. The reason for that, I am fairly certain that, is the if statement I referred to in my original email. I tried to write my observation and conclusions accurately, please bear that in mind while reading it, I appreciate that. Thank you.

(The socket between ReetiCapturing and FaceDETECTION.dll is fixed and tested so I am not referring to that at all).

Morteza

**Comment by mbehrooz** [comment]
Ok so I think it works. It is apparently the case that when Java restarts the line series of plugins being loaded do not show up, but there is a single line that says Not saving into user model in red. That must be a restart and after that (bringing the urbi server back up) pushing a button causes robot to act and talk...

**Comment by mbehrooz** [comment]
Ok sure I will keep testing it and once resolved move to Calendar.

Yours, M
