### ISSUE TITLE
Calendar infinite loop

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#367]
@mbehrooz

The Calendar appeared to go into an infinite loop (CPU pinned and no output) when adding a weekly repeating reminder.  Below are the log files taken after I killed the system:

https://www.dropbox.com/s/dlbw41ycm4pk0cy/User.Calendar-Loop.owl
https://www.dropbox.com/s/3hs4s3uvgaihzto/User.Calendar-Loop.txt

And here is the log file at the _start_ of the session:

https://www.dropbox.com/s/plfnot64d4o2lmf/User.Calendar-Loop-Start.owl

Notice there were already some reminds in the calendar.

**Comment by mbehrooz** [comment]
Just as a feedback this must be the same as the other similar issue.
