### ISSUE TITLE
crash of engagement

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#369]
this bug occurred when I loaded up the system in Stranger mode, got hte agent (who said Hi) and then I walked away for 10 minutes.

https://www.dropbox.com/s/axu66xqb0nzcp1c/User.2014-06-02_11_39_13.txt
https://www.dropbox.com/s/m465z457tbank4v/User.2014-06-02_11_39_13.owl

**Comment by candysidner** [comment]
Fixed.
