### ISSUE TITLE
Dead system (

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#370]
I ws working my way through putting an event of each type in the calendar  I got several items put in the calendar, but when I created a phone call event, the agent went ot set it up and then simply never did anything else.  The .txt file does not show any null pointers or like errors.

Note also that as I added more events, it got slower putting them after there were about 7 events.

https://www.dropbox.com/s/q8akm7rm8oitolh/User.2014-06-02_12_01_49.owl
https://www.dropbox.com/s/z3zquopma96r9hx/User.2014-06-02_12_01_49.txt

**Comment by charlesrich** [comment]
I did not mean to close this issue.

**Comment by charlesrich** [comment]
Note that the Java SessionSchema says "not responding".

This issue was created by Candy

**Comment by charlesrich** [comment]
In a second run, activities from the previous run were available (due to their storage in the User model).  I continued to add activities, and the system went dead (again with no information in the .txt dump) after 4 more entries.

https://www.dropbox.com/s/ocfjg9ffv3kd4qt/User.2014-06-02_12_18_45.owl
https://www.dropbox.com/s/vt7zxvg7fuvjuf9/User.2014-06-02_12_18_45.txt

**Comment by charlesrich** [comment]
In this use of  calendar, the system also did not respond and when I looked at the Java schema session, it produced the last 2 lines in the .txt file below.

https://www.dropbox.com/s/noyb0q4zlf9b1ck/User.2014-06-02_12_32_38.txt
https://www.dropbox.com/s/ki1kmr97dsc0klv/User.2014-06-02_12_32_38.owl

**Comment by candysidner** [comment]
Morteza has been able to reproduce this general behavior we don't need multiple copies of issue.
