### ISSUE TITLE
Nutrition NullPointerException

### ISSUE THREAD

**Issue by candysidner** [always-on/always#372]
@lring @zessiez 

More important, nutrition crashed when it was done with the session, although the Disco-RT system was able to carry on after the crash.  See NullPointerException in scriptbuilder code in log below (may be same as #363)

https://www.dropbox.com/s/60byz8e83t2y345/User.2014-06-02_13_08_39.owl
https://www.dropbox.com/s/1zgqciyznr9c3rd/User.2014-06-02_13_08_39.txt

**Comment by zessie** [comment]
I was not able to reproduce this bug. Try the newer version, and it may have been fixed.
