### ISSUE TITLE
Nutrition Diary page not appearing

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#375]
@lring @zessiez

Candy has reported this twice (including most recently today), but it might be intermittent, since it appeared the one time I tried.

**Comment by zessiez** [comment]
I am working on this right now.

**Comment by candysidner** [comment]
@lring @zessiez @candysidner

It sounds like this is a race condition.  Loading and then displaying images in AWT is actually not straightword.  You have to wait until the image is fully loaded.  See details, e.g., at:

http://stackoverflow.com/questions/7225957/java-awt-image-from-file

**Comment by zessiez** [comment]
I can repeat that bug right now and I am fixing it.

**Comment by charlesrich** [comment]
@candysidner 

Please confirm fixed and then close.
