### ISSUE TITLE
Anecdotes (telling an interesting story) called on nuitrition tips

### ISSUE THREAD

**Issue by candysidner** [always-on/always#378]
@lring When I asked the agent for an interesting story, as you will see in the dump below, it gave me a healthy eating tip, which is NOT what it should do. Search for "User says "Hear something interesting." to find the start of the problem.

https://www.dropbox.com/s/hb9myflpwhzoglv/User.2014-06-02_16_39_15.txt
https://www.dropbox.com/s/h4ftw57fr17jh3v/User.2014-06-02_16_39_15.owl

**Comment by charlesrich** [comment]
@lring @candysidner 

I think this came up before and I was told that these tips are part of the "interesting" data base, which is why the entry was renamed "something interesting" (rather than "story").  If this is confirmed, maybe Candy needs to change the text in the explanation plugin?

**Comment by candysidner** [comment]
Thanks Lazlo!  If you decide to keep it, I will change the explanation plugin to be more explicit. It's not a big change so let me know.
Candy
On Jun 2, 2014, at 5:27 PM, Charles Rich notifications@github.com wrote:

> @lring @candysidner
> 
> I think this came up before and I was told that these tips are part of the "interesting" data base, which is why the entry was renamed "something interesting" (rather than "story"). If this is confirmed, maybe Candy needs to change the text in the explanation plugin?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Candace L. Sidner, Ph.D.
Research Professor
Department of Computer Science
Worcester Polytechnic Institute
(508) 831-6637
http://candysidner.com
sidner@wpi.edu
