### ISSUE TITLE
Calendar is missing people to have meals, meetings etc with; one other bug

### ISSUE THREAD

**Issue by candysidner** [always-on/always#381]
@mbehrooz
I have tested calendar extensively yesterday and today.  The agent no longer asks you who the meal or phone call or whatever is with.  It used to show a list of names.  However, it also used to be stupid and ask about friends for medical appts.  So it needs ot ask this and needs to do it for the appropriate events.  
Second bug:  When agent asks the event type, if you press "something else" it thinks it has put up the keyboard, but it doesn't.  If you say I'm done, it has an event with no name that it puts in the calendar.  Look for "something else" in the txt file below.

https://www.dropbox.com/s/tmk4qx3vnw8q2fd/User.2014-06-03_17_05_16.txt
https://www.dropbox.com/s/p8lhyxujjdnmxlh/User.2014-06-03_17_05_16.owl

**Comment by mbehrooz** [comment]
I look into the first bug, the second one is already reported and has an open issue. Thanks. @candysidner

**Comment by mbehrooz** [comment]
@candysidner Ok I fixed the first bug too, I will send a pull request shortly. Thanks.

**Comment by mbehrooz** [comment]
Also, I can make it not ask for friends for a specific type of event, just let me know what types please!

**Comment by candysidner** [comment]
I will do this but I have to run the thing to decide which they are.  I know it makes sense for phone calls, meals, coffee, birthday.

Not for community meetings, religious services, travel, medical appoints.  

I will run calendar after dinner (we are starving--it's 7:30!).
c.
On Jun 3, 2014, at 6:56 PM, Morteza Behrooz notifications@github.com wrote:

> I look into the first bug, the second one is already reported and has an open issue. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Candace L. Sidner, Ph.D.
Research Professor
Department of Computer Science
Worcester Polytechnic Institute
(508) 831-6637
http://candysidner.com
sidner@wpi.edu

**Comment by charlesrich** [comment]
@candysidner 

Please go back and test that it asks for people for correct events.
