### ISSUE TITLE
Calendar doubles added events when it repeats a statement to user

### ISSUE THREAD

**Issue by candysidner** [always-on/always#389]
When the user steps away after the agent is putting an added event in the calendar and the agent repeats itself, it puts 2 copies of the event in the calendar (at the same time).

Search for "Okay, here is the entry."

https://www.dropbox.com/s/hlsy7sfm9xm0ltv/User.2014-06-05_10_45_00.txt
https://www.dropbox.com/s/d9l559woxdrxb0e/User.2014-06-05_10_45_00.owl

**Comment by charlesrich** [comment]
This could be a general problem when MTSM states with "side efffects" are repeated due to timeout (and maybe the same for "What did you say?").  Need to investigate.

**Comment by candysidner** [comment]
Similar effect of putting up fresh KB is take too long typing.
