### ISSUE TITLE
OWL inconsistency during Enroll

### ISSUE THREAD

**Issue by candysidner** [always-on/always#399]
see 
https://www.dropbox.com/s/sfn917ukbzisxhe/User.2014-06-12_10_44_50.txt

https://www.dropbox.com/s/vl4p19n03m98v9w/User.2014-06-12_10_44_50.owl

https://www.dropbox.com/s/dwxyh6bs3abm928/User.2014-06-12_10_44_50.csv

**Comment by charlesrich** [comment]
Need to temporarily turn off incremental consistency checking to see inconsistency.

But first catch the NullPointerException!

**Comment by charlesrich** [comment]
Error does _not_ occur with incremental consistency checking turned off.

Removing sister assertion removes error with incremental on.   

Leave incremental _OFF_ for now.

-CR
