### ISSUE TITLE
exception in Enroll schema

### ISSUE THREAD

**Issue by candysidner** [always-on/always#409]
Not sure what this is. It happened when I clicked no to a question for an entry
https://www.dropbox.com/s/38ejns3kxr0yv9j/User.2014-06-16_10_53_39.txt

https://www.dropbox.com/s/jk98xidwwfdjnpx/User.2014-06-16_10_53_39.owl

https://www.dropbox.com/s/8q6w15de963cp6r/User.2014-06-16_10_53_39.csv

**Comment by charlesrich** [comment]
Fixed
