### ISSUE TITLE
bug in enroll

### ISSUE THREAD

**Issue by candysidner** [always-on/always#423]
when starting with a new user, I added two people.  When I went to edit one of the properties of the second person, the system kept the information about the first person in memory (even though it showed the results for the second peson on the screen).

https://www.dropbox.com/s/mtmo915txi3rieh/User.2014-07-01_15_21_49.txt
https://www.dropbox.com/s/xy9k8t5ze8d2nim/User.2014-07-01_15_21_49.csv
https://www.dropbox.com/s/4c6l87gv1qfhqpp/User.2014-07-01_15_21_49.owl

**Comment by charlesrich** [comment]
I think I fixed it, but good idea to test all cases of enroll edit again.
