### ISSUE TITLE
Exercise Plugin mentions very old date

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#455]
@lring @zessiez

In log file below notice agent says:

Did you  <GESTURE hand=\"L\" cmd=\"BEAT\"/> get a  <EYEBROWS DIR=\"UP\"/> <GESTURE hand=\"L\" cmd=\"BEAT\"/> chance  <EYEBROWS DIR=\"DOWN\"/> to  <GESTURE hand=\"L\" cmd=\"BEAT\"/> go for a  <GESTURE hand=\"L\" cmd=\"BEAT\"/> walk WEDNESDAY, OCTOBER 12 ?

whereas current date was November 11.  I looked in user model file (.owl linked below), but did not see any stale date info, but maybe I missed it.   -CR

https://www.dropbox.com/s/jnacmlwq16674oj/User.2014-11-11_21_34_28.txt?dl=0
https://www.dropbox.com/s/fkvhsjsoz5eueje/User.2014-11-11_21_34_28.csv?dl=0
https://www.dropbox.com/s/d6wm1v5bblmmocx/User.2014-11-11_21_34_28.owl?dl=0

**Comment by zessie** [comment]
This has been fixed. Lazlo is working on a new push request at this point.

**Comment by charlesrich** [comment]
Candy to close when verified by testing.
