### ISSUE TITLE
Video Storytelling app dies when user says Let's record

### ISSUE THREAD

**Issue by candysidner** [always-on/always#474]
The video storytelling app dies at the point that the user clicks on Let's record.  The camera blue light ends when this app starts, and so the question is what makes this app die (and kill the system).
I've put the cvs, txt and owl files here:
https://www.dropbox.com/s/f6djnkooilvj9mm/User.2014-12-12_09_23_49.owl?dl=0
https://www.dropbox.com/s/qsf64nh7w0bssi2/User.2014-12-12_09_23_49.txt?dl=0
https://www.dropbox.com/s/u9qus9waek9pt1d/User.2014-12-12_09_24_03.csv?dl=0

**Comment by candysidner** [comment]
Note that if I stop the app before the "let's record" request, everythign is fine!
Candy

**Comment by charlesrich** [comment]
@lring @candysidner 
Unfortunately, the new changes to FaceDetection did not fix this error.  See fresh log files below.  Note that the Shore Engine is successfully stopped (and blue light went out) and the story.startRecording message is sent.   It appears that the client is not responding at this point.  Note the system started normally on this run, i.e., the face perceptor was using the camera until it gave it up.

https://www.dropbox.com/s/kgxmaoz40r5azub/User.2014-12-13_15_07_45.txt?dl=0
https://www.dropbox.com/s/qwa8itbidawrxmg/User.2014-12-13_15_07_45.csv?dl=0
https://www.dropbox.com/s/1986l4dq9y4f24s/User.2014-12-13_15_07_45.owl?dl=0

**Comment by charlesrich** [comment]
Ok, will wait for pull request to test.

On Sun, Dec 14, 2014 at 1:56 PM, lring notifications@github.com wrote:

> Fixed in latest push, a dll was missing.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/always-on/always/issues/474#issuecomment-66924606.

## 

Dr. Charles Rich, Professor, Computer Science Department
http://www.cs.wpi.edu
Interactive Media and Game Development Program
http://www.wpi.edu/academics/imgd/
Robotics Engineering Program http://www.wpi.edu/academics/robotics/
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich
