### ISSUE TITLE
Hangout window appears after user rejects call

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#484]
@lring @candysidner 

Now that videoCallRejected message is being correctly sent (latest push), a new/old bug has shown up:  After the call is rejected, the dialogue continues correctly, but the screen becomes _divided_ with the picture of the remote hangout person on the left side.  It is as if on the client side, the plugin has gone ahead and set up for the call even though it has been rejected.

**Comment by lring** [comment]
This issue should be closed now?
