### ISSUE TITLE
Reeti FaceDetection.DLL: Connection closed

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#491]
@lring 
As per your comment last night, I think there may indeed be a bug in the way the error handling was recoded in FaceDetection for the case when Reeti is running.

In particular, I kept getting these error messages at startup:

 FaceDetection.DLL: Could not connect socket, retrying in 10s...
 FaceDetection.DLL: Could not connect socket, retrying in 10s...
 FaceDetection.DLL: Connection closed

followed by the Java process exiting (and sometimes not preceded by the retry messages).   I believe the Java process is supposed to keep retrying.

Tx, -CR

**Comment by lring** [comment]
I just looked into this issue.

Reeti uses it's own camera for face detection by giving a socket connection to shore for it to work with.

If it is not working I would guess this is a software related issue with what is running on the Reeti.

@mshayganfar Do you have any ideas?

**Comment by candysidner** [comment]
Yes, this is a Reeti-specific issue. Restarting of Reeti for each session needs to be reviewed.
