### ISSUE TITLE
Change calendar columns in weekly calendar to show dates

### ISSUE THREAD

**Issue by candysidner** [always-on/always#498]
Currently the days of the week in a week view of the calendar are long enough to make the date of the week run off the column.  Switch to using day abbreviations (Mon, Tues) etc.  Hopefully that will fix the problem.

**Comment by charlesrich** [comment]
Duplicate

**Comment by charlesrich** [comment]
@lring   

HELP!!  I changed the labels in Calendar.UI/WeekPanel.xaml from "Monday" to "Mon", etc., and did a complete clean and rebuild, but the old labels ("Monday") still keep showing up in the calendar!   I have done this multiple times and ways with no avail.  There must be something about how VS works I don't understand.

Anyways, I committed the changed files--could you please try to make this work!?  Tx, -Chuck

**Comment by charlesrich** [comment]
I even tried manually deleting the bin and obj folders for Calendar.UI and Plugins.Startup.  And I searched both VS and Eclipse for any occurrences of "Monday"---none.

I really cannot figure out where it is caching the old layout...

Maybe we need to ask someone who is a WPF expert?

-CR

**Comment by lring** [comment]
Hey Chuck,

Sorry for the delayed response, I was out of the office today.

I will check on it first thing tomorrow morning.

--Lazlo

**Comment by charlesrich** [comment]
DUH.  The "Monday" etc., in the xaml file were only a distraction.  The actual labels are computing on the fly in Java using DateTimeFormat.   All I had to do was change the format template.
