### ISSUE TITLE
Remove email address from enrollment

### ISSUE THREAD

**Issue by lring** [always-on/always#508]
@charlesrich @candysidner 

I don't see the purpose of asking for the participants email during the enrollment process, as far as I know it is not used anywhere in the system.

**Comment by candysidner** [comment]
Ah isn't that what is used for video calls?

c.
On Jan 16, 2015, at 11:31 AM, lring <notifications@github.com> wrote:

> @charlesrich @candysidner
> 
> I don't see the purpose of asking for the participants email during the enrollment process, as far as I know it is not used anywhere in the system.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

----------------------------------
Candace L. Sidner, Ph.D.
Research Professor
Department of Computer Science
Worcester Polytechnic Institute
(508) 831-6637
http://candysidner.com
sidner@wpi.edu

**Comment by lring** [comment]
For the video calls we use unique accounts for each computer since we have
to register them with the google api.

Also we would need to know there password in order to use their email,
which I'm guessing most participants would have a problem with.

**Comment by candysidner** [comment]
Lazlo,

Oh, I just realized what you mean.  The user's email address, not the friends/family!  Yes, we don't need it.  I assume Chuck can take care of this!

Candy
On Jan 16, 2015, at 2:08 PM, lring <notifications@github.com> wrote:

> For the video calls we use unique accounts for each computer since we have 
> to register them with the google api. 
> 
> Also we would need to know there password in order to use their email, 
> which I'm guessing most participants would have a problem with. 
> 
> On Fri, Jan 16, 2015 at 2:04 PM, candysidner <notifications@github.com> 
> wrote: 
> 
> > Ah isn't that what is used for video calls? 
> > 
> > c. 
> > On Jan 16, 2015, at 11:31 AM, lring <notifications@github.com> wrote: 
> > 
> > > @charlesrich @candysidner 
> > > 
> > > I don't see the purpose of asking for the participants email during the 
> > enrollment process, as far as I know it is not used anywhere in the system. 
> > > 
> > > — 
> > > Reply to this email directly or view it on GitHub. 
> > > 
> > 
> > ---------------------------------- 
> > Candace L. Sidner, Ph.D. 
> > Research Professor 
> > Department of Computer Science 
> > Worcester Polytechnic Institute 
> > (508) 831-6637 
> > http://candysidner.com 
> > sidner@wpi.edu 
> > 
> > — 
> > Reply to this email directly or view it on GitHub 
> > <https://github.com/always-on/always/issues/508#issuecomment-70304315>. 
> >
> —
> Reply to this email directly or view it on GitHub.
> 

----------------------------------
Candace L. Sidner, Ph.D.
Research Professor
Department of Computer Science
Worcester Polytechnic Institute
(508) 831-6637
http://candysidner.com
sidner@wpi.edu

**Comment by charlesrich** [comment]
Done. -CR
