### ISSUE TITLE
Make Reeti's lips move

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#66]
I think this may be where you need to get 'bookmarks' in ttsCallbackListener marking the start and end of the speaking.  I will send Lazlo a message about this to see if he needs to add something.   Please look to see what kind of mouth movements Reeti uses in its native demos for speaking.

**Comment by mshayganfar** [comment]
I used "viseme" and I changed my code in the Reeti side. Since the bottom lip motor is not working. I tested the changes of the visemes using LEDs on Reeti's face.  As of now, whenever the agent talks, the color of LEDs are changing and it stops when the agent stops talking.

**Comment by charlesrich** [comment]
I think this works as well as it is going to, but I need to confirm with video.

**Comment by mshayganfar** [comment]
We can close this issue now.
