### ISSUE TITLE
Reverse images on HP camera

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#67]
The images on the HP are reversed (left/right) from the images on the ASUS, so tracking will work backwards :-)

The solution is to put a switch in ShoreFacePerceptor which detects the HP and reverses the numbers in the FacePerception object. 

Mohammad:  Could you please do this asap?  

First thing to try is System.getProperty("os.arch"), which returns "amd64" on my ASUS.   Can you test if returns something different on the HP's?

If not, then use System.getenv("COMPUTERNAME") and check a list of known HP computer names.

**Comment by mshayganfar** [comment]
This issue has been done. I am going to send an e-mail about this.

**Comment by charlesrich** [comment]
Apparently this was never really an issue, but a misunderstanding by Ayesha.
