### ISSUE TITLE
Improve virtual agent gaze tracking

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#68]
(1)  She still does not seem to be looking at me.  I think The problem is that the location of the agent's body is _offset_ (to her left) from the camera (which is above center of the screen).  I think we need to add an extra parameter to GazeRealizer to adjust for this.  Do you see what I mean?

Furthermore, when the screen is in "plugin mode" (e.g., for TTT), she is offset to the _right_, so this parameter needs to be different.  The system knows when it is changing modes.

So I think we need two int constants in GazeRealizer, OFFSET and OFFSET_PLUGIN (whose values depend on the art design of client).   I will define a method to check which mode the system is and then leave it to you to get the math right.   I'll let you know when you can update from upstream.

(2) After the "head dance" in the Stranger hello greeting, it looks like her head gets "stuck" looking to her right until I move a little bit and then it picks up tracking.  

(3) Don't forget to initialize the position in the realizer constructor with Proxy.getGazeHor() and Proxy.getGazeVer().  Note Chuck may not yet have done Issue #96 to set these yet, but agent code should use them.

(4)  I notice that you reduced the amount of head turning on the agent tracking.   I think this is a bad idea, because with the narrow field of view of the camera, the total amount the agent ever turns her head is so little, you really lose the effect.   Do you agree? Could you please experiment with increasing the factor.

(5)  It occurs to me that there is a conceptual problem with this code, which is that the thresholds are all in terms of pixels, which assumes that there is a fixed frame rate.  This is definitely not true, since the PERCEPTOR_INTERVAL could be changed, and even if it is not, the time between calls to run is variable depending on system load.  So don't you think the thresholds should be in terms of pixels per unit time, i.e., you need to remember the time corresponding to prevInfo also?

**Comment by mshayganfar** [comment]
I worked on the agent's body offset issue and I believe with the current "tuning" values, the agent's gaze is acceptable in both small and big positions.

PS. The amount of head turning is not limited any more. (issue #4 above)

**Comment by mshayganfar** [comment]
This is totally done.

**Comment by charlesrich** [comment]
I just need to confirm it on my machine.

**Comment by charlesrich** [comment]
After latest update (March 23), In full-screen size, if I sit directly centered in front of the camera (which is in the middle of the screen), the agent appears to be looking straight ahead, and therefore not directly at me (since her head is located a bit off-center).    She should in fact be looking a tiny to her left.

Since this is the most common use case, I think it is needs to be tweaked to be better. 

When the plugin is visible, I think the angle is better.

**Comment by mshayganfar** [comment]
We can also close this issue if you like the direction of the gazes when user sits right at the middle.
