### ISSUE TITLE
Sometimes need to click menu twice

### ISSUE THREAD

**Issue by charlesrich** [always-on/always#93]
Both Candy and I have noticed that sometimes you need to click a second time on a menu item for the system to respond.   It seems intermittent, but quite common.  Note that the box does change color momentarily, but the choices doesn't "take".

**Comment by charlesrich** [comment]
That's an interesting thought---I will follow it up and get back to you.

-Chuck

On Thu, Feb 6, 2014 at 5:09 PM, lring notifications@github.com wrote:

> @charlesrich https://github.com/charlesrich I think I may have finally
> found the source of this bug. From what I can tell it has to do with the
> disco dialogue manager in the background taking focus away from the client.
> Is there some way to disable the disco pop up window to check this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/always-on/always/issues/93#issuecomment-34338477
> .

## 

Dr. Charles Rich, Professor, Computer Science Departmenthttp://www.cs.wpi.edu
Interactive Media and Game Development
Programhttp://www.wpi.edu/academics/imgd/
Robotics Engineering Program http://www.wpi.edu/academics/robotics/
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

**Comment by charlesrich** [comment]
Hi Lazo, I did some experimentation and I think there are in fact _two_
problems going on.  One is in fact some focus-stealing.  This is what
happens when you first click on a button and nothing changes (you just
changed the focus).  You can get rid of focus stealing by completely hiding
the Disco windows by (temporarily) changing setVisible(true) to setVisible(false)
in edu.wpi.disco.rt.DiscoRT.configure() and the constructor of edu.wpi.always.com.schemas.DiscoActivitySchema.

But then you will notice another intermittent behavior in which when you
click on a button the first time, it turns blue, but the rest of the
buttons don't disappear as usual.

Please see if you can reproduce this---it doesn't happen all the time, so
it is a real pain

-Chuck

On Thu, Feb 6, 2014 at 6:31 PM, Charles Rich rich@wpi.edu wrote:

> That's an interesting thought---I will follow it up and get back to you.
> 
> -Chuck
> 
> On Thu, Feb 6, 2014 at 5:09 PM, lring notifications@github.com wrote:
> 
> > @charlesrich https://github.com/charlesrich I think I may have finally
> > found the source of this bug. From what I can tell it has to do with the
> > disco dialogue manager in the background taking focus away from the client.
> > Is there some way to disable the disco pop up window to check this?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/always-on/always/issues/93#issuecomment-34338477
> > .
> 
> ## 
> 
> Dr. Charles Rich, Professor, Computer Science Departmenthttp://www.cs.wpi.edu
> Interactive Media and Game Development Programhttp://www.wpi.edu/academics/imgd/
> Robotics Engineering Program http://www.wpi.edu/academics/robotics/
> Worcester Polytechnic Institute, Fuller Laboratories B25b
> 100 Institute Road, Worcester, MA 01609-2280
> 
> Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
> Home: http://www.cs.wpi.edu/~rich

## 

Dr. Charles Rich, Professor, Computer Science Departmenthttp://www.cs.wpi.edu
Interactive Media and Game Development
Programhttp://www.wpi.edu/academics/imgd/
Robotics Engineering Program http://www.wpi.edu/academics/robotics/
Worcester Polytechnic Institute, Fuller Laboratories B25b
100 Institute Road, Worcester, MA 01609-2280

Email: rich@wpi.edu   Phone: 508-831-5945   Fax: 508-831-5776
Home: http://www.cs.wpi.edu/~rich

**Comment by candysidner** [comment]
@lring

The Disco windows are now not present in release mode, so if there is any double-clicking happening it is solely due to the client.  Not sure if there still is.

**Comment by charlesrich** [comment]
@lring @candysidner  
I am tentatively closing this issue because Candy has not had any problems with double-clicking since I totally removed the Disco windows in release mode.   If she sees the problem again, we will revisit it.

-CR
